---
- name: Create user in Windows
  hosts: win
  gather_facts: yes
  ignore_errors: yes
  ignore_unreachable: yes

  vars_files: user_create_password.yml

  vars:
    user_json_file: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_output_windows_user_create.json"

  vars_prompt:
    - name: group
      prompt: Enter group for creating user
      private: no

  tasks:
    - name: Task 1 - Create local user
      win_user:
        name: local_abc1
        password: "{{ win_password }}"
        group: "{{ group }}"
        state: present
      register: user_output

    - name: Task 2 - Store User creation output to log file
      copy:
        dest: "{{ user_json_file }}"
        content: |
          {% for host in groups.linux %}
          { 'ip': '{{ ansible_host }}', 'server_name': '{{ host }}', 'os_distribution': '{{ ansible_os }}', 'data' : {{hostvars[host].user_output}} }
          {% endfor %}
      delegate_to: localhost
